ConfigFile:          "config.yml" 
LogLevel:            "info"           
DeploymentMode:      "dev"           
AllowCrossOrigin:     true          
CharSet:             "UTF-8"


Database:
  UserID: "postgres"
  Passwd: "postgres"
  Port: "5400"
  IP: "127.0.0.1"
  Name: "VERLOOP"

Verloop:
  Port: "9090"